# Generated by Django 2.1.7 on 2019-05-14 05:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('costo', models.IntegerField()),
                ('cant_modulos', models.IntegerField()),
                ('observacion', models.TextField(blank=True, max_length=2000, null=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Inscrito',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=70)),
                ('apellidos', models.CharField(max_length=70)),
                ('dni', models.IntegerField()),
                ('e_mail', models.EmailField(max_length=254)),
                ('telefono', models.IntegerField()),
                ('direccion', models.CharField(max_length=150, null=True)),
                ('observacion', models.TextField(blank=True, max_length=2000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('modulos_entregados', models.CharField(blank=True, max_length=2000, null=True)),
                ('asesora', models.CharField(max_length=50, null=True)),
                ('beneficiario', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_matricula', models.DateTimeField(null=True)),
                ('fecha_diploma', models.DateField(null=True)),
                ('promocion', models.CharField(max_length=200, null=True)),
                ('descuento_actual', models.IntegerField(null=True)),
                ('descuento_pendiente', models.IntegerField(null=True)),
                ('observacion', models.TextField(blank=True, max_length=2000, null=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.Curso')),
                ('inscrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.Inscrito')),
            ],
        ),
        migrations.CreateModel(
            name='Ugel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('director', models.CharField(max_length=100)),
                ('observacion', models.TextField(blank=True, max_length=2000, null=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='inscrito',
            name='ugel',
            field=models.ForeignKey(blank=True, null=True, on_delete='CASCADE', to='academico.Ugel'),
        ),
    ]
