# Generated by Django 2.1.7 on 2019-05-14 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inscrito',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='curso',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='inscrito',
            name='dni',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='inscrito',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='fecha_matricula',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='modulos_entregados',
            field=models.TextField(blank=True, max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='ugel',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
